[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18" 